---
- name: Instalar dependências
  ansible.builtin.apt:
    name: 
      - gnupg2
    state: present

- name: Instalar Memcached
  ansible.builtin.apt:
    name: memcached
    state: present
    update_cache: yes

- name: Garantir serviço ativo
  ansible.builtin.systemd:
    name: memcached
    enabled: yes
    state: started