---
# Versão do GLPI
glpi_version: "10.0.17"

# Configurações gerais
glpi_url: "glpi.local"
timezone: "America/Sao_Paulo"

# Configurações do banco
db_host: "{{ hostvars['mariadb1']['ansible_host'] }}"
db_name: "glpi"
db_user: "glpi"
db_password: "semsenhaglpi"

# Configurações de cache
memcached_server: "{{ hostvars['memcached1']['ansible_host'] }}"

# Configurações do PHP
php_memory_limit: "256M"
php_max_execution_time: "600"
php_upload_max_filesize: "20M"
php_post_max_size: "20M"