---
- name: Alterar senha dos usuários padrão
  ansible.builtin.shell: |
    echo yes | php /opt/glpi/bin/console user:reset_password -p semsenhaglpi {{ item }}
  loop:
    - post-only
    - tech
    - normal
    - glpi
    - glpi-system

- name: Configurar CRON do GLPI
  ansible.builtin.cron:
    name: "GLPI Cron"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: www-data
    job: "/usr/bin/php -f /opt/glpi/front/cron.php"