---
- name: Configurar pacotes
  ansible.builtin.import_tasks: 01-instalacao.yml
  tags:
    - glpi
    - glpi:pacotes

- name: Aplicar configuração
  ansible.builtin.import_tasks: 02-configuracao.yml
  tags:
    - glpi
    - glpi:configuracao

- name: Instalar configurações extras
  ansible.builtin.import_tasks: 03-post-config.yml
  tags:
    - glpi
    - glpi:post-config