# ansible/playbook.yml
---
- name: Configurações base para todas as máquinas
  hosts: glpi
  become: true
  gather_facts: true
  roles:
    - role: sistema
      tags:
        - sistema
        - todas

- name: Configurar HAProxy
  hosts: haproxy1
  become: true
  gather_facts: true
  roles:
    - role: haproxy
      tags:
        - haproxy
        - todas